import { defineConfig } from 'vitepress'

export default defineConfig({
	title: 'js-cool',
	base: '/js-cool/',

	head: [
		['link', { rel: 'icon', href: '/js-cool/logo.svg' }],
		['meta', { name: 'theme-color', content: '#3eaf7c' }],
	],

	locales: {
		root: {
			label: 'English',
			lang: 'en',
			title: 'js-cool',
			description: 'A modern JavaScript utility library',
			themeConfig: {
				nav: [
					{ text: 'Guide', link: '/guide/', activeMatch: '/guide/' },
					{ text: 'API', link: '/api/', activeMatch: '/api/' },
					{ text: 'Examples', link: '/examples/', activeMatch: '/examples/' },
					{
						text: 'Links',
						items: [
							{ text: 'GitHub', link: 'https://github.com/saqqdy/js-cool' },
							{ text: 'NPM', link: 'https://www.npmjs.com/package/js-cool' },
						],
					},
				],
				sidebar: {
					'/guide/': [
						{
							text: 'Getting Started',
							items: [
								{ text: 'Introduction', link: '/guide/' },
								{ text: 'Installation', link: '/guide/installation' },
								{ text: 'Quick Start', link: '/guide/quick-start' },
							],
						},
						{
							text: 'Basics',
							items: [
								{ text: 'String', link: '/guide/string' },
								{ text: 'Array', link: '/guide/array' },
								{ text: 'Object', link: '/guide/object' },
								{ text: 'URL', link: '/guide/url' },
								{ text: 'DOM', link: '/guide/dom' },
								{ text: 'Storage', link: '/guide/storage' },
								{ text: 'Type Check', link: '/guide/type-check' },
							],
						},
					],
					'/api/': [
						{
							text: 'API Reference',
							items: [{ text: 'Overview', link: '/api/' }],
						},
						{
							text: 'String',
							items: [
								{ text: 'camel2Dash', link: '/api/string/camel2-dash' },
								{ text: 'dash2Camel', link: '/api/string/dash2-camel' },
								{ text: 'upperFirst', link: '/api/string/upper-first' },
								{ text: 'encodeBase64', link: '/api/string/encode-base64' },
								{ text: 'decodeBase64', link: '/api/string/decode-base64' },
								{ text: 'encodeUtf8', link: '/api/string/encode-utf8' },
								{ text: 'decodeUtf8', link: '/api/string/decode-utf8' },
								{ text: 'escape', link: '/api/string/escape' },
								{ text: 'unescape', link: '/api/string/unescape' },
								{ text: 'trim', link: '/api/string/trim' },
								{ text: 'clearHtml', link: '/api/string/clear-html' },
								{ text: 'cutCHSString', link: '/api/string/cut-chs-string' },
								{ text: 'getCHSLength', link: '/api/string/get-chs-length' },
								{ text: 'mapTemplate', link: '/api/string/map-template' },
							],
						},
						{
							text: 'Array',
							items: [
								{ text: 'unique', link: '/api/array/unique' },
								{ text: 'shuffle', link: '/api/array/shuffle' },
								{ text: 'sorter', link: '/api/array/sorter' },
								{ text: 'intersect', link: '/api/array/intersect' },
								{ text: 'union', link: '/api/array/union' },
								{ text: 'minus', link: '/api/array/minus' },
								{ text: 'complement', link: '/api/array/complement' },
								{ text: 'contains', link: '/api/array/contains' },
								{ text: 'all', link: '/api/array/all' },
								{ text: 'any', link: '/api/array/any' },
								{ text: 'searchObject', link: '/api/array/search-object' },
								{ text: 'arrayToCSV', link: '/api/array/array-to-csv' },
								{ text: 'CSVToArray', link: '/api/array/csv-to-array' },
								{ text: 'randomNumbers', link: '/api/array/random-numbers' },
							],
						},
						{
							text: 'Object',
							items: [
								{ text: 'clone', link: '/api/object/clone' },
								{ text: 'extend', link: '/api/object/extend' },
								{ text: 'cleanData', link: '/api/object/clean-data' },
								{ text: 'getProperty', link: '/api/object/get-property' },
								{ text: 'setProperty', link: '/api/object/set-property' },
								{ text: 'isEqual', link: '/api/object/is-equal' },
								{ text: 'getType', link: '/api/object/get-type' },
								{ text: 'isArray', link: '/api/object/is-array' },
								{ text: 'isObject', link: '/api/object/is-object' },
								{ text: 'isPlainObject', link: '/api/object/is-plain-object' },
								{ text: 'isDate', link: '/api/object/is-date' },
								{ text: 'isRegExp', link: '/api/object/is-reg-exp' },
								{ text: 'isWindow', link: '/api/object/is-window' },
								{ text: 'isIterable', link: '/api/object/is-iterable' },
								{ text: 'isDigitals', link: '/api/object/is-digitals' },
								{ text: 'safeParse', link: '/api/object/safe-parse' },
								{ text: 'safeStringify', link: '/api/object/safe-stringify' },
							],
						},
						{
							text: 'URL',
							items: [
								{ text: 'getUrlParams', link: '/api/url/get-url-params' },
								{ text: 'getUrlParam', link: '/api/url/get-url-param' },
								{ text: 'parseUrlParam', link: '/api/url/parse-url-param' },
								{ text: 'spliceUrlParam', link: '/api/url/splice-url-param' },
								{ text: 'getDirParam', link: '/api/url/get-dir-param' },
								{ text: 'client', link: '/api/url/client' },
								{ text: 'appVersion', link: '/api/url/app-version' },
								{ text: 'browserVersion', link: '/api/url/browser-version' },
								{ text: 'compareVersion', link: '/api/url/compare-version' },
								{ text: 'nextVersion', link: '/api/url/next-version' },
							],
						},
						{
							text: 'DOM',
							items: [
								{ text: 'addEvent', link: '/api/dom/add-event' },
								{ text: 'removeEvent', link: '/api/dom/remove-event' },
								{ text: 'stopDefault', link: '/api/dom/stop-default' },
								{ text: 'stopBubble', link: '/api/dom/stop-bubble' },
								{ text: 'copy', link: '/api/dom/copy' },
								{ text: 'getScrollPosition', link: '/api/dom/get-scroll-position' },
								{ text: 'windowSize', link: '/api/dom/window-size' },
								{ text: 'isDarkMode', link: '/api/dom/is-dark-mode' },
								{ text: 'inBrowser', link: '/api/dom/in-browser' },
								{ text: 'inNodeJs', link: '/api/dom/in-node-js' },
								{ text: 'preloader', link: '/api/dom/preloader' },
								{ text: 'openUrl', link: '/api/dom/open-url' },
							],
						},
						{
							text: 'Storage',
							items: [
								{ text: 'setCache', link: '/api/storage/set-cache' },
								{ text: 'getCache', link: '/api/storage/get-cache' },
								{ text: 'delCache', link: '/api/storage/del-cache' },
								{ text: 'setSession', link: '/api/storage/set-session' },
								{ text: 'getSession', link: '/api/storage/get-session' },
								{ text: 'delSession', link: '/api/storage/del-session' },
								{ text: 'setCookie', link: '/api/storage/set-cookie' },
								{ text: 'getCookie', link: '/api/storage/get-cookie' },
								{ text: 'getCookies', link: '/api/storage/get-cookies' },
								{ text: 'delCookie', link: '/api/storage/del-cookie' },
							],
						},
						{
							text: 'Convert',
							items: [
								{ text: 'arrayBufferToBase64', link: '/api/convert/array-buffer-to-base64' },
								{ text: 'base64ToArrayBuffer', link: '/api/convert/base64-to-array-buffer' },
								{ text: 'arrayBufferToBlob', link: '/api/convert/array-buffer-to-blob' },
								{ text: 'blobToArrayBuffer', link: '/api/convert/blob-to-array-buffer' },
								{ text: 'blobToBase64', link: '/api/convert/blob-to-base64' },
								{ text: 'base64ToBlob', link: '/api/convert/base64-to-blob' },
								{ text: 'fileToBase64', link: '/api/convert/file-to-base64' },
								{ text: 'base64ToFile', link: '/api/convert/base64-to-file' },
								{ text: 'blobToUrl', link: '/api/convert/blob-to-url' },
								{ text: 'urlToBlob', link: '/api/convert/url-to-blob' },
								{ text: 'svgToBlob', link: '/api/convert/svg-to-blob' },
								{ text: 'RGBToHex', link: '/api/convert/rgb-to-hex' },
							],
						},
						{
							text: 'Utility',
							items: [
								{ text: 'delay', link: '/api/utility/delay' },
								{ text: 'waiting', link: '/api/utility/waiting' },
								{ text: 'uuid', link: '/api/utility/uuid' },
								{ text: 'fingerprint', link: '/api/utility/fingerprint' },
								{ text: 'randomString', link: '/api/utility/random-string' },
								{ text: 'randomColor', link: '/api/utility/random-color' },
								{ text: 'randomNumber', link: '/api/utility/random-number' },
								{ text: 'fixNumber', link: '/api/utility/fix-number' },
								{ text: 'toThousands', link: '/api/utility/to-thousands' },
								{ text: 'nextIndex', link: '/api/utility/next-index' },
								{ text: 'pattern', link: '/api/utility/pattern' },
								{ text: 'promiseFactory', link: '/api/utility/promise-factory' },
							],
						},
					],
				},
				editLink: {
					pattern: 'https://github.com/saqqdy/js-cool/edit/master/docs/:path',
					text: 'Edit this page on GitHub',
				},
				footer: {
					message: 'Released under the MIT License.',
					copyright: 'Copyright © 2024-present saqqdy',
				},
				docFooter: { prev: 'Previous', next: 'Next' },
				outline: { label: 'On this page' },
				lastUpdated: {
					text: 'Last updated',
					formatOptions: { dateStyle: 'medium', timeStyle: 'short' },
				},
				langMenuLabel: 'Language',
				returnToTopLabel: 'Return to top',
				sidebarMenuLabel: 'Menu',
				darkModeSwitchLabel: 'Theme',
				lightModeSwitchTitle: 'Switch to light theme',
				darkModeSwitchTitle: 'Switch to dark theme',
			},
		},
		zh: {
			label: '简体中文',
			lang: 'zh-CN',
			title: 'js-cool',
			description: '现代 JavaScript 工具库',
			link: '/zh/',
			themeConfig: {
				nav: [
					{ text: '指南', link: '/zh/guide/', activeMatch: '/zh/guide/' },
					{ text: 'API', link: '/zh/api/', activeMatch: '/zh/api/' },
					{ text: '示例', link: '/zh/examples/', activeMatch: '/zh/examples/' },
					{
						text: '链接',
						items: [
							{ text: 'GitHub', link: 'https://github.com/saqqdy/js-cool' },
							{ text: 'NPM', link: 'https://www.npmjs.com/package/js-cool' },
						],
					},
				],
				sidebar: {
					'/zh/guide/': [
						{
							text: '开始',
							items: [
								{ text: '介绍', link: '/zh/guide/' },
								{ text: '安装', link: '/zh/guide/installation' },
								{ text: '快速上手', link: '/zh/guide/quick-start' },
							],
						},
						{
							text: '基础',
							items: [
								{ text: '字符串', link: '/zh/guide/string' },
								{ text: '数组', link: '/zh/guide/array' },
								{ text: '对象', link: '/zh/guide/object' },
								{ text: 'URL', link: '/zh/guide/url' },
								{ text: 'DOM', link: '/zh/guide/dom' },
								{ text: '存储', link: '/zh/guide/storage' },
								{ text: '类型检查', link: '/zh/guide/type-check' },
							],
						},
					],
					'/zh/api/': [
						{
							text: 'API 参考',
							items: [{ text: '概览', link: '/zh/api/' }],
						},
						{
							text: '字符串',
							items: [
								{ text: 'camel2Dash', link: '/zh/api/string/camel2-dash' },
								{ text: 'dash2Camel', link: '/zh/api/string/dash2-camel' },
								{ text: 'upperFirst', link: '/zh/api/string/upper-first' },
								{ text: 'encodeBase64', link: '/zh/api/string/encode-base64' },
								{ text: 'decodeBase64', link: '/zh/api/string/decode-base64' },
								{ text: 'encodeUtf8', link: '/zh/api/string/encode-utf8' },
								{ text: 'decodeUtf8', link: '/zh/api/string/decode-utf8' },
								{ text: 'escape', link: '/zh/api/string/escape' },
								{ text: 'unescape', link: '/zh/api/string/unescape' },
								{ text: 'trim', link: '/zh/api/string/trim' },
								{ text: 'clearHtml', link: '/zh/api/string/clear-html' },
								{ text: 'cutCHSString', link: '/zh/api/string/cut-chs-string' },
								{ text: 'getCHSLength', link: '/zh/api/string/get-chs-length' },
								{ text: 'mapTemplate', link: '/zh/api/string/map-template' },
							],
						},
						{
							text: '数组',
							items: [
								{ text: 'unique', link: '/zh/api/array/unique' },
								{ text: 'shuffle', link: '/zh/api/array/shuffle' },
								{ text: 'sorter', link: '/zh/api/array/sorter' },
								{ text: 'intersect', link: '/zh/api/array/intersect' },
								{ text: 'union', link: '/zh/api/array/union' },
								{ text: 'minus', link: '/zh/api/array/minus' },
								{ text: 'complement', link: '/zh/api/array/complement' },
								{ text: 'contains', link: '/zh/api/array/contains' },
								{ text: 'all', link: '/zh/api/array/all' },
								{ text: 'any', link: '/zh/api/array/any' },
								{ text: 'searchObject', link: '/zh/api/array/search-object' },
								{ text: 'arrayToCSV', link: '/zh/api/array/array-to-csv' },
								{ text: 'CSVToArray', link: '/zh/api/array/csv-to-array' },
								{ text: 'randomNumbers', link: '/zh/api/array/random-numbers' },
							],
						},
						{
							text: '对象',
							items: [
								{ text: 'clone', link: '/zh/api/object/clone' },
								{ text: 'extend', link: '/zh/api/object/extend' },
								{ text: 'cleanData', link: '/zh/api/object/clean-data' },
								{ text: 'getProperty', link: '/zh/api/object/get-property' },
								{ text: 'setProperty', link: '/zh/api/object/set-property' },
								{ text: 'isEqual', link: '/zh/api/object/is-equal' },
								{ text: 'getType', link: '/zh/api/object/get-type' },
								{ text: 'isArray', link: '/zh/api/object/is-array' },
								{ text: 'isObject', link: '/zh/api/object/is-object' },
								{ text: 'isPlainObject', link: '/zh/api/object/is-plain-object' },
								{ text: 'isDate', link: '/zh/api/object/is-date' },
								{ text: 'isRegExp', link: '/zh/api/object/is-reg-exp' },
								{ text: 'isWindow', link: '/zh/api/object/is-window' },
								{ text: 'isIterable', link: '/zh/api/object/is-iterable' },
								{ text: 'isDigitals', link: '/zh/api/object/is-digitals' },
								{ text: 'safeParse', link: '/zh/api/object/safe-parse' },
								{ text: 'safeStringify', link: '/zh/api/object/safe-stringify' },
							],
						},
						{
							text: 'URL',
							items: [
								{ text: 'getUrlParams', link: '/zh/api/url/get-url-params' },
								{ text: 'getUrlParam', link: '/zh/api/url/get-url-param' },
								{ text: 'parseUrlParam', link: '/zh/api/url/parse-url-param' },
								{ text: 'spliceUrlParam', link: '/zh/api/url/splice-url-param' },
								{ text: 'getDirParam', link: '/zh/api/url/get-dir-param' },
								{ text: 'client', link: '/zh/api/url/client' },
								{ text: 'appVersion', link: '/zh/api/url/app-version' },
								{ text: 'browserVersion', link: '/zh/api/url/browser-version' },
								{ text: 'compareVersion', link: '/zh/api/url/compare-version' },
								{ text: 'nextVersion', link: '/zh/api/url/next-version' },
							],
						},
						{
							text: 'DOM',
							items: [
								{ text: 'addEvent', link: '/zh/api/dom/add-event' },
								{ text: 'removeEvent', link: '/zh/api/dom/remove-event' },
								{ text: 'stopDefault', link: '/zh/api/dom/stop-default' },
								{ text: 'stopBubble', link: '/zh/api/dom/stop-bubble' },
								{ text: 'copy', link: '/zh/api/dom/copy' },
								{ text: 'getScrollPosition', link: '/zh/api/dom/get-scroll-position' },
								{ text: 'windowSize', link: '/zh/api/dom/window-size' },
								{ text: 'isDarkMode', link: '/zh/api/dom/is-dark-mode' },
								{ text: 'inBrowser', link: '/zh/api/dom/in-browser' },
								{ text: 'inNodeJs', link: '/zh/api/dom/in-node-js' },
								{ text: 'preloader', link: '/zh/api/dom/preloader' },
								{ text: 'openUrl', link: '/zh/api/dom/open-url' },
							],
						},
						{
							text: '存储',
							items: [
								{ text: 'setCache', link: '/zh/api/storage/set-cache' },
								{ text: 'getCache', link: '/zh/api/storage/get-cache' },
								{ text: 'delCache', link: '/zh/api/storage/del-cache' },
								{ text: 'setSession', link: '/zh/api/storage/set-session' },
								{ text: 'getSession', link: '/zh/api/storage/get-session' },
								{ text: 'delSession', link: '/zh/api/storage/del-session' },
								{ text: 'setCookie', link: '/zh/api/storage/set-cookie' },
								{ text: 'getCookie', link: '/zh/api/storage/get-cookie' },
								{ text: 'getCookies', link: '/zh/api/storage/get-cookies' },
								{ text: 'delCookie', link: '/zh/api/storage/del-cookie' },
							],
						},
						{
							text: '转换',
							items: [
								{ text: 'arrayBufferToBase64', link: '/zh/api/convert/array-buffer-to-base64' },
								{ text: 'base64ToArrayBuffer', link: '/zh/api/convert/base64-to-array-buffer' },
								{ text: 'arrayBufferToBlob', link: '/zh/api/convert/array-buffer-to-blob' },
								{ text: 'blobToArrayBuffer', link: '/zh/api/convert/blob-to-array-buffer' },
								{ text: 'blobToBase64', link: '/zh/api/convert/blob-to-base64' },
								{ text: 'base64ToBlob', link: '/zh/api/convert/base64-to-blob' },
								{ text: 'fileToBase64', link: '/zh/api/convert/file-to-base64' },
								{ text: 'base64ToFile', link: '/zh/api/convert/base64-to-file' },
								{ text: 'blobToUrl', link: '/zh/api/convert/blob-to-url' },
								{ text: 'urlToBlob', link: '/zh/api/convert/url-to-blob' },
								{ text: 'svgToBlob', link: '/zh/api/convert/svg-to-blob' },
								{ text: 'RGBToHex', link: '/zh/api/convert/rgb-to-hex' },
							],
						},
						{
							text: '工具',
							items: [
								{ text: 'delay', link: '/zh/api/utility/delay' },
								{ text: 'waiting', link: '/zh/api/utility/waiting' },
								{ text: 'uuid', link: '/zh/api/utility/uuid' },
								{ text: 'fingerprint', link: '/zh/api/utility/fingerprint' },
								{ text: 'randomString', link: '/zh/api/utility/random-string' },
								{ text: 'randomColor', link: '/zh/api/utility/random-color' },
								{ text: 'randomNumber', link: '/zh/api/utility/random-number' },
								{ text: 'fixNumber', link: '/zh/api/utility/fix-number' },
								{ text: 'toThousands', link: '/zh/api/utility/to-thousands' },
								{ text: 'nextIndex', link: '/zh/api/utility/next-index' },
								{ text: 'pattern', link: '/zh/api/utility/pattern' },
								{ text: 'promiseFactory', link: '/zh/api/utility/promise-factory' },
							],
						},
					],
				},
				editLink: {
					pattern: 'https://github.com/saqqdy/js-cool/edit/master/docs/:path',
					text: '在 GitHub 上编辑此页',
				},
				footer: {
					message: '基于 MIT 许可发布',
					copyright: '版权所有 © 2024-present saqqdy',
				},
				docFooter: { prev: '上一页', next: '下一页' },
				outline: { label: '页面导航' },
				lastUpdated: {
					text: '最后更新于',
					formatOptions: { dateStyle: 'medium', timeStyle: 'short' },
				},
				langMenuLabel: '语言',
				returnToTopLabel: '回到顶部',
				sidebarMenuLabel: '菜单',
				darkModeSwitchLabel: '主题',
				lightModeSwitchTitle: '切换到浅色模式',
				darkModeSwitchTitle: '切换到深色模式',
			},
		},
	},

	themeConfig: {
		logo: '/logo.svg',
		siteTitle: 'js-cool',
		socialLinks: [
			{ icon: 'github', link: 'https://github.com/saqqdy/js-cool' },
		],
		search: {
			provider: 'local',
		},
	},
})
