import { defineConfig } from 'vitepress'

export default defineConfig({
	base: '/js-cool/',
	vite: {
		build: {
			chunkSizeWarningLimit: 1000,
		},
	},
	head: [
		['link', { href: '/js-cool/logo.svg', rel: 'icon' }],
		['meta', { name: 'theme-color', content: '#3eaf7c' }],
	],

	locales: {
		root: {
			description: 'A modern JavaScript utility library',
			label: 'English',
			lang: 'en',
			themeConfig: {
				darkModeSwitchLabel: 'Theme',
				darkModeSwitchTitle: 'Switch to dark theme',
				docFooter: { next: 'Next', prev: 'Previous' },
				editLink: {
					pattern: 'https://github.com/saqqdy/js-cool/edit/master/docs/:path',
					text: 'Edit this page on GitHub',
				},
				footer: {
					copyright: 'Copyright © 2024-present saqqdy',
					message: 'Released under the MIT License.',
				},
				langMenuLabel: 'Language',
				lastUpdated: {
					formatOptions: { dateStyle: 'medium', timeStyle: 'short' },
					text: 'Last updated',
				},
				lightModeSwitchTitle: 'Switch to light theme',
				nav: [
					{ activeMatch: '/guide/', link: '/guide/', text: 'Guide' },
					{ activeMatch: '/api/', link: '/api/', text: 'API' },
					{ activeMatch: '/examples/', link: '/examples/', text: 'Examples' },
					{
						items: [
							{ link: 'https://github.com/saqqdy/js-cool', text: 'GitHub' },
							{ link: 'https://www.npmjs.com/package/js-cool', text: 'NPM' },
						],
						text: 'Links',
					},
				],
				outline: { label: 'On this page' },
				returnToTopLabel: 'Return to top',
				sidebar: {
					'/api/': [
						{
							items: [{ link: '/api/', text: 'Overview' }],
							text: 'API Reference',
						},
						{
							collapsed: false,
							items: [
								{ link: '/api/string/camel2-dash', text: 'camel2Dash' },
								{ link: '/api/string/dash2-camel', text: 'dash2Camel' },
								{ link: '/api/string/upper-first', text: 'upperFirst' },
								{ link: '/api/string/kebab-case', text: 'kebabCase' },
								{ link: '/api/string/snake-case', text: 'snakeCase' },
								{ link: '/api/string/truncate', text: 'truncate' },
								{ link: '/api/string/clear-html', text: 'clearHtml' },
								{ link: '/api/string/clear-attr', text: 'clearAttr' },
								{ link: '/api/string/cut-chs-string', text: 'cutCHSString' },
								{ link: '/api/string/get-chs-length', text: 'getCHSLength' },
								{ link: '/api/string/map-template', text: 'mapTemplate' },
								{ link: '/api/string/template', text: 'template' },
								{ link: '/api/string/words', text: 'words' },
								{ link: '/api/string/escape', text: 'escape' },
								{ link: '/api/string/unescape', text: 'unescape' },
							],
							text: 'String',
						},
						{
							collapsed: true,
							items: [
								{ link: '/api/array/unique', text: 'unique' },
								{ link: '/api/array/shuffle', text: 'shuffle' },
								{ link: '/api/array/sorter', text: 'sorter' },
								{ link: '/api/array/sort-pinyin', text: 'sortPinyin' },
								{ link: '/api/array/chunk', text: 'chunk' },
								{ link: '/api/array/flatten', text: 'flatten' },
								{ link: '/api/array/group-by', text: 'groupBy' },
								{ link: '/api/array/key-by', text: 'keyBy' },
								{ link: '/api/array/sample', text: 'sample' },
								{ link: '/api/array/sample-size', text: 'sampleSize' },
								{ link: '/api/array/intersect', text: 'intersect' },
								{ link: '/api/array/union', text: 'union' },
								{ link: '/api/array/minus', text: 'minus' },
								{ link: '/api/array/complement', text: 'complement' },
								{ link: '/api/array/contains', text: 'contains' },
								{ link: '/api/array/all', text: 'all' },
								{ link: '/api/array/any', text: 'any' },
								{ link: '/api/array/search-object', text: 'searchObject' },
							],
							text: 'Array',
						},
						{
							collapsed: true,
							items: [
								{ link: '/api/object/clone', text: 'clone' },
								{ link: '/api/object/extend', text: 'extend' },
								{ link: '/api/object/get-property', text: 'getProperty' },
								{ link: '/api/object/set-property', text: 'setProperty' },
								{ link: '/api/object/omit', text: 'omit' },
								{ link: '/api/object/pick', text: 'pick' },
								{ link: '/api/object/clean-data', text: 'cleanData' },
								{ link: '/api/object/merge-with', text: 'mergeWith' },
								{ link: '/api/object/transform', text: 'transform' },
								{ link: '/api/object/safe-parse', text: 'safeParse' },
								{ link: '/api/object/safe-stringify', text: 'safeStringify' },
								{ link: '/api/array/array-to-csv', text: 'arrayToCSV' },
								{ link: '/api/array/csv-to-array', text: 'CSVToArray' },
								{ link: '/api/convert/csv-to-json', text: 'CSVToJSON' },
								{ link: '/api/convert/json-to-csv', text: 'JSONToCSV' },
							],
							text: 'Object',
						},
						{
							collapsed: true,
							items: [
								{ link: '/api/object/get-type', text: 'getType' },
								{ link: '/api/object/is-array', text: 'isArray' },
								{ link: '/api/object/is-object', text: 'isObject' },
								{ link: '/api/object/is-plain-object', text: 'isPlainObject' },
								{ link: '/api/object/is-date', text: 'isDate' },
								{ link: '/api/object/is-reg-exp', text: 'isRegExp' },
								{ link: '/api/object/is-window', text: 'isWindow' },
								{ link: '/api/object/is-iterable', text: 'isIterable' },
								{ link: '/api/object/is-equal', text: 'isEqual' },
								{ link: '/api/object/is-empty', text: 'isEmpty' },
								{ link: '/api/object/is-nil', text: 'isNil' },
								{ link: '/api/object/is-exits-function', text: 'isExitsFunction' },
							],
							text: 'Type Check',
						},
						{
							collapsed: true,
							items: [
								{ link: '/api/validate/is-email', text: 'isEmail' },
								{ link: '/api/validate/is-phone', text: 'isPhone' },
								{ link: '/api/validate/is-url', text: 'isURL' },
								{ link: '/api/validate/is-id-card', text: 'isIDCard' },
								{ link: '/api/validate/is-credit-card', text: 'isCreditCard' },
							],
							text: 'Validate',
						},
						{
							collapsed: true,
							items: [
								{ link: '/api/url/Url-class', text: 'Url' },
								{ link: '/api/url/url', text: 'url' },
								{ link: '/api/url/get-dir-params', text: 'getDirParams' },
								{ link: '/api/url/ua', text: 'ua' },
								{ link: '/api/url/app-version', text: 'appVersion' },
								{ link: '/api/url/browser-version', text: 'browserVersion' },
								{ link: '/api/url/os-version', text: 'osVersion' },
								{ link: '/api/url/compare-version', text: 'compareVersion' },
								{ link: '/api/url/next-version', text: 'nextVersion' },
							],
							text: 'URL & Browser',
						},
						{
							collapsed: true,
							items: [
								{ link: '/api/dom/add-event', text: 'addEvent' },
								{ link: '/api/dom/remove-event', text: 'removeEvent' },
								{ link: '/api/dom/stop-bubble', text: 'stopBubble' },
								{ link: '/api/dom/stop-default', text: 'stopDefault' },
								{ link: '/api/dom/copy', text: 'copy' },
								{ link: '/api/dom/window-size', text: 'windowSize' },
								{ link: '/api/dom/is-dark-mode', text: 'isDarkMode' },
								{ link: '/api/dom/in-browser', text: 'inBrowser' },
								{ link: '/api/dom/in-node-js', text: 'inNodeJs' },
								{ link: '/api/dom/is-number-browser', text: 'isNumberBrowser' },
								{ link: '/api/dom/preloader', text: 'preloader' },
								{ link: '/api/dom/open-url', text: 'openUrl' },
							],
							text: 'DOM',
						},
						{
							collapsed: true,
							items: [{ link: '/api/scroll/', text: 'scroll' }],
							text: 'Scroll',
						},
						{
							collapsed: true,
							items: [{ link: '/api/storage/', text: 'storage' }],
							text: 'Storage',
						},
{
							collapsed: true,
							items: [
								{ link: '/api/convert/csv-to-json', text: 'CSVToJSON' },
								{ link: '/api/convert/json-to-csv', text: 'JSONToCSV' },
								{ link: '/api/convert/rgb-to-hex', text: 'RGBToHex' },
							],
							text: 'Convert',
						},
						{
							collapsed: true,
							items: [
								{ link: '/api/number/clamp', text: 'clamp' },
								{ link: '/api/number/round', text: 'round' },
								{ link: '/api/number/sum', text: 'sum' },
								{ link: '/api/number/average', text: 'average' },
								{ link: '/api/number/in-range', text: 'inRange' },
								{ link: '/api/utility/fix-number', text: 'fixNumber' },
								{ link: '/api/utility/to-thousands', text: 'toThousands' },
							],
							text: 'Number',
						},
						{
							collapsed: true,
							items: [
								{ link: '/api/date/format-date', text: 'formatDate' },
								{ link: '/api/date/date-diff', text: 'dateDiff' },
								{ link: '/api/date/relative-time', text: 'relativeTime' },
								{ link: '/api/date/is-today', text: 'isToday' },
								{ link: '/api/date/get-days-in-month', text: 'getDaysInMonth' },
							],
							text: 'Date',
						},
						{
							collapsed: true,
							items: [
								{ link: '/api/color/hex-to-rgb', text: 'hexToRGB' },
								{ link: '/api/color/rgb-to-hsl', text: 'rgbToHSL' },
								{ link: '/api/color/lighten', text: 'lighten' },
								{ link: '/api/color/darken', text: 'darken' },
								{ link: '/api/color/is-light-color', text: 'isLightColor' },
							],
							text: 'Color',
						},
						{
							collapsed: true,
							items: [
								{ link: '/api/utility/delay', text: 'delay' },
								{ link: '/api/utility/waiting', text: 'waiting' },
								{ link: '/api/utility/uuid', text: 'uuid' },
								{ link: '/api/utility/fingerprint', text: 'fingerprint' },
								{ link: '/api/utility/random-string', text: 'randomString' },
								{ link: '/api/utility/random-color', text: 'randomColor' },
								{ link: '/api/utility/random-number', text: 'randomNumber' },
								{ link: '/api/array/random-numbers', text: 'randomNumbers' },
								{ link: '/api/utility/next-index', text: 'nextIndex' },
								{ link: '/api/utility/patterns', text: 'patterns' },
								{ link: '/api/utility/promise-factory', text: 'promiseFactory' },
								{ link: '/api/utility/punctual-timer', text: 'punctualTimer' },
								{ link: '/api/utility/get-file-type', text: 'getFileType' },
								{ link: '/api/utility/get-number', text: 'getNumber' },
							],
							text: 'Utility',
						},
						{
							collapsed: true,
							items: [
								{ link: '/api/async/debounce', text: 'debounce' },
								{ link: '/api/async/throttle', text: 'throttle' },
								{ link: '/api/async/retry', text: 'retry' },
							],
							text: 'Async Flow',
						},
						{
							collapsed: true,
							items: [
								{ link: '/api/string/encode-utf8', text: 'encodeUtf8' },
								{ link: '/api/string/decode-utf8', text: 'decodeUtf8' },
								{ link: '/api/string/encode-base64', text: 'encodeBase64' },
								{ link: '/api/string/decode-base64', text: 'decodeBase64' },
							],
							text: 'Encode',
						},
						{
							collapsed: true,
							items: [{ link: '/api/network/fill-ipv6', text: 'fillIPv6' }],
							text: 'Network',
						},
						{
							collapsed: true,
							items: [
								{ link: '/api/binary/', text: 'Overview' },
								{ link: '/api/binary/from', text: 'from' },
								{ link: '/api/binary/parse', text: 'parse' },
								{ link: '/api/binary/compare', text: 'compare' },
								{ link: '/api/binary/clone', text: 'clone' },
								{ link: '/api/binary/download', text: 'download' },
								{ link: '/api/binary/base64', text: 'base64' },
								{ link: '/api/binary/blob', text: 'blob' },
								{ link: '/api/binary/array-buffer', text: 'arrayBuffer' },
								{ link: '/api/binary/file', text: 'file' },
								{ link: '/api/binary/url', text: 'url' },
								{ link: '/api/binary/svg', text: 'svg' },
								{ link: '/api/binary/text', text: 'text' },
								{ link: '/api/binary/data-url', text: 'dataURL' },
								{ link: '/api/binary/hex', text: 'hex' },
								{ link: '/api/binary/hash', text: 'hash' },
								{ link: '/api/binary/meta', text: 'meta' },
							],
							text: 'Binary',
						},
					],
					'/guide/': [
						{
							items: [
								{ link: '/guide/', text: 'Introduction' },
								{ link: '/guide/installation', text: 'Installation' },
								{ link: '/guide/quick-start', text: 'Quick Start' },
								{ link: '/guide/migration', text: 'Migration Guide' },
							],
							text: 'Getting Started',
						},
						{
							items: [
								{ link: '/guide/string', text: 'String' },
								{ link: '/guide/array', text: 'Array' },
								{ link: '/guide/object', text: 'Object' },
								{ link: '/guide/type-check', text: 'Type Check' },
								{ link: '/guide/validate', text: 'Validate' },
								{ link: '/guide/url', text: 'URL & Browser' },
								{ link: '/guide/dom', text: 'DOM' },
								{ link: '/guide/storage', text: 'Storage' },
								{ link: '/guide/number', text: 'Number' },
								{ link: '/guide/date', text: 'Date' },
								{ link: '/guide/color', text: 'Color' },
								{ link: '/guide/utility', text: 'Utility' },
							],
							text: 'Categories',
						},
					],
				},
				sidebarMenuLabel: 'Menu',
			},
			title: 'js-cool',
		},
		zh: {
			description: '现代 JavaScript 工具库',
			label: '简体中文',
			lang: 'zh-CN',
			link: '/zh/',
			themeConfig: {
				darkModeSwitchLabel: '主题',
				darkModeSwitchTitle: '切换到深色模式',
				docFooter: { next: '下一页', prev: '上一页' },
				editLink: {
					pattern: 'https://github.com/saqqdy/js-cool/edit/master/docs/:path',
					text: '在 GitHub 上编辑此页',
				},
				footer: {
					copyright: '版权所有 © 2024-present saqqdy',
					message: '基于 MIT 许可发布',
				},
				langMenuLabel: '语言',
				lastUpdated: {
					formatOptions: { dateStyle: 'medium', timeStyle: 'short' },
					text: '最后更新于',
				},
				lightModeSwitchTitle: '切换到浅色模式',
				nav: [
					{ activeMatch: '/zh/guide/', link: '/zh/guide/', text: '指南' },
					{ activeMatch: '/zh/api/', link: '/zh/api/', text: 'API' },
					{ activeMatch: '/zh/examples/', link: '/zh/examples/', text: '示例' },
					{
						items: [
							{ link: 'https://github.com/saqqdy/js-cool', text: 'GitHub' },
							{ link: 'https://www.npmjs.com/package/js-cool', text: 'NPM' },
						],
						text: '链接',
					},
				],
				outline: { label: '页面导航' },
				returnToTopLabel: '回到顶部',
				sidebar: {
					'/zh/api/': [
						{
							items: [{ link: '/zh/api/', text: '概览' }],
							text: 'API 参考',
						},
						{
							collapsed: false,
							items: [
								{ link: '/zh/api/string/camel2-dash', text: 'camel2Dash' },
								{ link: '/zh/api/string/dash2-camel', text: 'dash2Camel' },
								{ link: '/zh/api/string/upper-first', text: 'upperFirst' },
									{ link: '/zh/api/string/lower-first', text: 'lowerFirst' },
									{ link: '/zh/api/string/capitalize', text: 'capitalize' },
								{ link: '/zh/api/string/kebab-case', text: 'kebabCase' },
								{ link: '/zh/api/string/snake-case', text: 'snakeCase' },
								{ link: '/zh/api/string/truncate', text: 'truncate' },
								{ link: '/zh/api/string/trim', text: 'trim' },
								{ link: '/zh/api/string/clear-html', text: 'clearHtml' },
								{ link: '/zh/api/string/clear-attr', text: 'clearAttr' },
								{ link: '/zh/api/string/cut-chs-string', text: 'cutCHSString' },
								{ link: '/zh/api/string/get-chs-length', text: 'getCHSLength' },
								{ link: '/zh/api/string/map-template', text: 'mapTemplate' },
								{ link: '/zh/api/string/template', text: 'template' },
								{ link: '/zh/api/string/words', text: 'words' },
								{ link: '/zh/api/string/escape', text: 'escape' },
								{ link: '/zh/api/string/unescape', text: 'unescape' },
							],
							text: '字符串',
						},
						{
							collapsed: true,
							items: [
								{ link: '/zh/api/array/unique', text: 'unique' },
								{ link: '/zh/api/array/shuffle', text: 'shuffle' },
								{ link: '/zh/api/array/sorter', text: 'sorter' },
								{ link: '/zh/api/array/sort-pinyin', text: 'sortPinyin' },
								{ link: '/zh/api/array/chunk', text: 'chunk' },
								{ link: '/zh/api/array/flatten', text: 'flatten' },
								{ link: '/zh/api/array/group-by', text: 'groupBy' },
								{ link: '/zh/api/array/key-by', text: 'keyBy' },
									{ link: '/zh/api/array/partition', text: 'partition' },
									{ link: '/zh/api/array/count-by', text: 'countBy' },
								{ link: '/zh/api/array/sample', text: 'sample' },
								{ link: '/zh/api/array/sample-size', text: 'sampleSize' },
									{ link: '/zh/api/array/take', text: 'take' },
									{ link: '/zh/api/array/take-right', text: 'takeRight' },
									{ link: '/zh/api/array/drop', text: 'drop' },
									{ link: '/zh/api/array/drop-right', text: 'dropRight' },
									{ link: '/zh/api/array/zip', text: 'zip' },
									{ link: '/zh/api/array/unzip', text: 'unzip' },
								{ link: '/zh/api/array/intersect', text: 'intersect' },
									{ link: '/zh/api/array/intersection-by', text: 'intersectionBy' },
								{ link: '/zh/api/array/union', text: 'union' },
									{ link: '/zh/api/array/union-by', text: 'unionBy' },
								{ link: '/zh/api/array/minus', text: 'minus' },
									{ link: '/zh/api/array/difference-by', text: 'differenceBy' },
								{ link: '/zh/api/array/complement', text: 'complement' },
								{ link: '/zh/api/array/contains', text: 'contains' },
									{ link: '/zh/api/array/find-index', text: 'findIndex' },
									{ link: '/zh/api/array/find-last-index', text: 'findLastIndex' },
								{ link: '/zh/api/array/all', text: 'all' },
								{ link: '/zh/api/array/any', text: 'any' },
								{ link: '/zh/api/array/search-object', text: 'searchObject' },
							],
							text: '数组',
						},
						{
							collapsed: true,
							items: [
								{ link: '/zh/api/object/clone', text: 'clone' },
								{ link: '/zh/api/object/extend', text: 'extend' },
								{ link: '/zh/api/object/get-property', text: 'getProperty' },
								{ link: '/zh/api/object/set-property', text: 'setProperty' },
								{ link: '/zh/api/object/omit', text: 'omit' },
								{ link: '/zh/api/object/pick', text: 'pick' },
									{ link: '/zh/api/object/map-keys', text: 'mapKeys' },
									{ link: '/zh/api/object/map-values', text: 'mapValues' },
									{ link: '/zh/api/object/invert', text: 'invert' },
								{ link: '/zh/api/object/clean-data', text: 'cleanData' },
								{ link: '/zh/api/object/merge-with', text: 'mergeWith' },
								{ link: '/zh/api/object/transform', text: 'transform' },
								{ link: '/zh/api/object/safe-parse', text: 'safeParse' },
								{ link: '/zh/api/object/safe-stringify', text: 'safeStringify' },
								{ link: '/zh/api/array/array-to-csv', text: 'arrayToCSV' },
								{ link: '/zh/api/array/csv-to-array', text: 'CSVToArray' },
								{ link: '/zh/api/convert/csv-to-json', text: 'CSVToJSON' },
								{ link: '/zh/api/convert/json-to-csv', text: 'JSONToCSV' },
							],
							text: '对象',
						},
						{
							collapsed: true,
							items: [
								{ link: '/zh/api/object/get-type', text: 'getType' },
								{ link: '/zh/api/object/is-array', text: 'isArray' },
								{ link: '/zh/api/object/is-object', text: 'isObject' },
								{ link: '/zh/api/object/is-plain-object', text: 'isPlainObject' },
								{ link: '/zh/api/object/is-date', text: 'isDate' },
								{ link: '/zh/api/object/is-reg-exp', text: 'isRegExp' },
								{ link: '/zh/api/object/is-window', text: 'isWindow' },
								{ link: '/zh/api/object/is-iterable', text: 'isIterable' },
								{ link: '/zh/api/object/is-equal', text: 'isEqual' },
								{ link: '/zh/api/object/is-empty', text: 'isEmpty' },
								{ link: '/zh/api/object/is-nil', text: 'isNil' },
								{
									link: '/zh/api/object/is-exits-function',
									text: 'isExitsFunction',
								},
							],
							text: '类型判断',
						},
						{
							collapsed: true,
							items: [
								{ link: '/zh/api/validate/is-email', text: 'isEmail' },
								{ link: '/zh/api/validate/is-phone', text: 'isPhone' },
								{ link: '/zh/api/validate/is-url', text: 'isURL' },
								{ link: '/zh/api/validate/is-id-card', text: 'isIDCard' },
								{ link: '/zh/api/validate/is-credit-card', text: 'isCreditCard' },
							],
							text: '验证函数',
						},
						{
							collapsed: true,
							items: [
								{ link: '/zh/api/url/Url-class', text: 'Url' },
								{ link: '/zh/api/url/url', text: 'url' },
								{ link: '/zh/api/url/get-dir-params', text: 'getDirParams' },
								{ link: '/zh/api/url/ua', text: 'ua' },
								{ link: '/zh/api/url/app-version', text: 'appVersion' },
								{ link: '/zh/api/url/browser-version', text: 'browserVersion' },
								{ link: '/zh/api/url/os-version', text: 'osVersion' },
								{ link: '/zh/api/url/compare-version', text: 'compareVersion' },
								{ link: '/zh/api/url/next-version', text: 'nextVersion' },
							],
							text: 'URL与浏览器',
						},
						{
							collapsed: true,
							items: [
								{ link: '/zh/api/dom/add-event', text: 'addEvent' },
								{ link: '/zh/api/dom/remove-event', text: 'removeEvent' },
								{ link: '/zh/api/dom/stop-bubble', text: 'stopBubble' },
								{ link: '/zh/api/dom/stop-default', text: 'stopDefault' },
								{ link: '/zh/api/dom/copy', text: 'copy' },
								{ link: '/zh/api/dom/window-size', text: 'windowSize' },
								{ link: '/zh/api/dom/is-dark-mode', text: 'isDarkMode' },
								{ link: '/zh/api/dom/in-browser', text: 'inBrowser' },
								{ link: '/zh/api/dom/in-node-js', text: 'inNodeJs' },
								{ link: '/zh/api/dom/is-number-browser', text: 'isNumberBrowser' },
								{ link: '/zh/api/dom/preloader', text: 'preloader' },
								{ link: '/zh/api/dom/open-url', text: 'openUrl' },
							],
							text: 'DOM',
						},
						{
							collapsed: true,
							items: [{ link: '/zh/api/scroll/', text: 'scroll' }],
							text: '滚动',
						},
						{
							collapsed: true,
							items: [{ link: '/zh/api/storage/', text: 'storage' }],
							text: '存储',
						},
{
							collapsed: true,
							items: [
								{ link: '/zh/api/convert/csv-to-json', text: 'CSVToJSON' },
								{ link: '/zh/api/convert/json-to-csv', text: 'JSONToCSV' },
								{ link: '/zh/api/convert/rgb-to-hex', text: 'RGBToHex' },
							],
							text: '转换',
						},
						{
							collapsed: true,
							items: [
								{ link: '/zh/api/number/clamp', text: 'clamp' },
								{ link: '/zh/api/number/round', text: 'round' },
								{ link: '/zh/api/number/sum', text: 'sum' },
								{ link: '/zh/api/number/average', text: 'average' },
								{ link: '/zh/api/number/in-range', text: 'inRange' },
								{ link: '/zh/api/utility/fix-number', text: 'fixNumber' },
								{ link: '/zh/api/utility/to-thousands', text: 'toThousands' },
							],
							text: '数字',
						},
						{
							collapsed: true,
							items: [
								{ link: '/zh/api/date/format-date', text: 'formatDate' },
								{ link: '/zh/api/date/date-diff', text: 'dateDiff' },
								{ link: '/zh/api/date/relative-time', text: 'relativeTime' },
								{ link: '/zh/api/date/is-today', text: 'isToday' },
								{ link: '/zh/api/date/get-days-in-month', text: 'getDaysInMonth' },
							],
							text: '日期',
						},
						{
							collapsed: true,
							items: [
								{ link: '/zh/api/color/hex-to-rgb', text: 'hexToRGB' },
								{ link: '/zh/api/color/rgb-to-hsl', text: 'rgbToHSL' },
								{ link: '/zh/api/color/lighten', text: 'lighten' },
								{ link: '/zh/api/color/darken', text: 'darken' },
								{ link: '/zh/api/color/is-light-color', text: 'isLightColor' },
							],
							text: '颜色',
						},
						{
							collapsed: true,
							items: [
								{ link: '/zh/api/utility/delay', text: 'delay' },
								{ link: '/zh/api/utility/waiting', text: 'waiting' },
								{ link: '/zh/api/utility/uuid', text: 'uuid' },
								{ link: '/zh/api/utility/fingerprint', text: 'fingerprint' },
								{ link: '/zh/api/utility/random-string', text: 'randomString' },
								{ link: '/zh/api/utility/random-color', text: 'randomColor' },
								{ link: '/zh/api/utility/random-number', text: 'randomNumber' },
								{ link: '/zh/api/array/random-numbers', text: 'randomNumbers' },
								{ link: '/zh/api/utility/next-index', text: 'nextIndex' },
								{ link: '/zh/api/utility/pattern', text: 'pattern' },
								{ link: '/zh/api/utility/promise-factory', text: 'promiseFactory' },
								{ link: '/zh/api/utility/punctual-timer', text: 'punctualTimer' },
								{ link: '/zh/api/utility/get-file-type', text: 'getFileType' },
								{ link: '/zh/api/utility/get-number', text: 'getNumber' },
							],
							text: '工具',
						},
						{
							collapsed: true,
							items: [
								{ link: '/zh/api/async/debounce', text: 'debounce' },
								{ link: '/zh/api/async/throttle', text: 'throttle' },
								{ link: '/zh/api/async/retry', text: 'retry' },
							],
							text: '异步流程',
						},
						{
							collapsed: true,
							items: [
								{ link: '/zh/api/string/encode-utf8', text: 'encodeUtf8' },
								{ link: '/zh/api/string/decode-utf8', text: 'decodeUtf8' },
								{ link: '/zh/api/string/encode-base64', text: 'encodeBase64' },
								{ link: '/zh/api/string/decode-base64', text: 'decodeBase64' },
							],
							text: '编码解码',
						},
						{
							collapsed: true,
							items: [{ link: '/zh/api/network/fill-ipv6', text: 'fillIPv6' }],
							text: '网络',
						},
						{
							collapsed: true,
							items: [
								{ link: '/zh/api/binary/', text: '概览' },
								{ link: '/zh/api/binary/from', text: 'from' },
								{ link: '/zh/api/binary/parse', text: 'parse' },
								{ link: '/zh/api/binary/compare', text: 'compare' },
								{ link: '/zh/api/binary/clone', text: 'clone' },
								{ link: '/zh/api/binary/download', text: 'download' },
								{ link: '/zh/api/binary/base64', text: 'base64' },
								{ link: '/zh/api/binary/blob', text: 'blob' },
								{ link: '/zh/api/binary/array-buffer', text: 'arrayBuffer' },
								{ link: '/zh/api/binary/file', text: 'file' },
								{ link: '/zh/api/binary/url', text: 'url' },
								{ link: '/zh/api/binary/svg', text: 'svg' },
								{ link: '/zh/api/binary/text', text: 'text' },
								{ link: '/zh/api/binary/data-url', text: 'dataURL' },
								{ link: '/zh/api/binary/hex', text: 'hex' },
								{ link: '/zh/api/binary/hash', text: 'hash' },
								{ link: '/zh/api/binary/meta', text: 'meta' },
							],
							text: '二进制',
						},
					],
					'/zh/guide/': [
						{
							items: [
								{ link: '/zh/guide/', text: '介绍' },
								{ link: '/zh/guide/installation', text: '安装' },
								{ link: '/zh/guide/quick-start', text: '快速上手' },
								{ link: '/zh/guide/migration', text: '迁移指南' },
							],
							text: '开始',
						},
						{
							items: [
								{ link: '/zh/guide/string', text: '字符串' },
								{ link: '/zh/guide/array', text: '数组' },
								{ link: '/zh/guide/object', text: '对象' },
								{ link: '/zh/guide/type-check', text: '类型判断' },
								{ link: '/zh/guide/validate', text: '验证函数' },
								{ link: '/zh/guide/url', text: 'URL与浏览器' },
								{ link: '/zh/guide/dom', text: 'DOM' },
								{ link: '/zh/guide/storage', text: '存储' },
								{ link: '/zh/guide/number', text: '数字' },
								{ link: '/zh/guide/date', text: '日期' },
								{ link: '/zh/guide/color', text: '颜色' },
								{ link: '/zh/guide/utility', text: '工具' },
							],
							text: '分类',
						},
					],
				},
				sidebarMenuLabel: '菜单',
			},
			title: 'js-cool',
		},
	},

	themeConfig: {
		logo: '/logo.svg',
		search: {
			provider: 'local',
		},
		siteTitle: 'js-cool',
		socialLinks: [{ icon: 'github', link: 'https://github.com/saqqdy/js-cool' }],
	},

	title: 'js-cool',
})
