/**
 * The opposite of mapValues, this method creates an object with the same keys as object
 * and values generated by running each own enumerable string keyed property of object thru iteratee.
 *
 * @example
 * ```js
 * mapKeys({ a: 1, b: 2 }, (value, key) => key + value)
 * // { a1: 1, b2: 2 }
 *
 * mapKeys({ a: 1, b: 2 }, 'prefix_')
 * // { prefix_a: 1, prefix_b: 2 }
 * ```
 * @since 6.0.0
 * @param object - The object to iterate over
 * @param iteratee - The function invoked per iteration
 * @returns - The new mapped object
 */
function mapKeys<T extends Record<string, unknown>>(
  object: T,
  iteratee: (value: T[keyof T], key: keyof T, object: T) => string
): Record<string, T[keyof T]> {
  const result: Record<string, T[keyof T]> = {}

  if (!object || typeof object !== 'object') return result

  for (const key in object) {
    if (Object.prototype.hasOwnProperty.call(object, key)) {
      const newKey = iteratee(object[key] as T[keyof T], key as keyof T, object)
      result[newKey] = object[key] as T[keyof T]
    }
  }

  return result
}

export default mapKeys
