/**
 * Creates an object with the same keys as object and values generated by running each
 * own enumerable string keyed property of object thru iteratee.
 *
 * @example
 * ```js
 * const users = {
 *   fred: { user: 'fred', age: 40 },
 *   pebbles: { user: 'pebbles', age: 1 }
 * }
 *
 * mapValues(users, ({ age }) => age)
 * // { fred: 40, pebbles: 1 }
 *
 * mapValues({ a: 1, b: 2 }, n => n * 2)
 * // { a: 2, b: 4 }
 *
 * mapValues({ a: { x: 1 }, b: { x: 2 } }, 'x')
 * // { a: 1, b: 2 }
 * ```
 * @since 6.0.0
 * @param object - The object to iterate over
 * @param iteratee - The function invoked per iteration or property name
 * @returns - The new mapped object
 */
function mapValues<T extends Record<string, unknown>, R>(
  object: T,
  iteratee: ((value: T[keyof T], key: keyof T, object: T) => R) | keyof T[keyof T]
): Record<keyof T, R> {
  const result = {} as Record<keyof T, R>

  if (!object || typeof object !== 'object') return result

  const getValue =
    typeof iteratee === 'function'
      ? iteratee
      : (value: T[keyof T]) => (value as Record<string, unknown>)?.[iteratee as string] as R

  for (const key in object) {
    if (Object.prototype.hasOwnProperty.call(object, key)) {
      result[key as keyof T] = getValue(object[key] as T[keyof T], key as keyof T, object)
    }
  }

  return result
}

export default mapValues
