name: npm-publish-test

on:
  push:
    branches: [master]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm build
        env:
          NODE_OPTIONS: --max-old-space-size=6144

      - name: TypeCheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test

      - name: Gen .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ./.npmrc

      - run: pnpm pub --test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: curl -X PUT -d "sync_upstream=true" "https://registry-direct.npmmirror.com/js-cool/sync"
